# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - end2endmlapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://end2endmlapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_414bcc27c90e4965816062fd44f9dab0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_40fb2ab2a12e41f589f4da320f5a1898 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: end2endmlapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_414bcc27c90e4965816062fd44f9dab0 }}/mlapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'end2endmlapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e475b93840aa4715a741dad2964925dd }}
        images: 'end2endmlapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_414bcc27c90e4965816062fd44f9dab0 }}/mlapp:${{ github.sha }}'